# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# TODO: Secure App ID and CLI_TOKEN

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor Production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:879743018506:android:935d8c6004a7e8b356e1f3",
    firebase_cli_token: "1//03paQnAYkEVz0CgYIARAAGAMSNwF-L9IrZb7kstRucu2PI-mYpLN6gAK9t_yU_pYpUJmtOIdy_4Goeae2t080_0Ia8em5tZpNoak",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "bastawiie@gmail.com",
    release_notes: "First Fastlane Firebase Distribution"
  )
  end
end